#!/usr/bin/env python3
"""Patch the HISE-generated AutogeneratedProject.jucer for CI builds (Windows).

Mirrors the inline patch the macOS job applies, plus Windows-specific fixes:
  - USE_IPP="1" -> "0" (runner has no Intel IPP; Kiss FFT fallback is fine)
  - strip IPP library attributes / include paths from the VS exporter
  - JUCE_VST3_CAN_REPLACE_VST2 -> 0 (public VST3 SDK has no vst2.x headers)
  - retarget a VS2017 exporter to VS2022 (windows-latest runners only ship
    the v143 toolset; HISE may emit a VS2017 exporter)
"""
import re
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    txt = f.read()
before = len(txt)

# --- IPP off (same as macOS job) ---
txt = txt.replace(' IPP1ALibrary="Static_Library"', '')
txt = re.sub(r'\sIPPLibrary="[^"]*"', '', txt)
txt = re.sub(r'extraLinkerFlags="[^"]*libipp[^"]*"', 'extraLinkerFlags=""', txt)
txt = re.sub(r'headerPath="[^"]*intel/ipp[^"]*"', 'headerPath=""', txt)
txt = re.sub(r'libraryPath="[^"]*intel/ipp[^"]*"', 'libraryPath=""', txt)
txt = re.sub(r'USE_IPP="1"', 'USE_IPP="0"', txt)

# --- VST2 compat off (same as macOS job) ---
if 'JUCE_VST3_CAN_REPLACE_VST2' in txt:
    txt = re.sub(r'JUCE_VST3_CAN_REPLACE_VST2="[01]"',
                 'JUCE_VST3_CAN_REPLACE_VST2="0"', txt)
else:
    txt = re.sub(r'(<JUCEOPTIONS\s)',
                 r'\1JUCE_VST3_CAN_REPLACE_VST2="0" ', txt, count=1)

# --- Retarget VS2017 exporter to VS2022 if no VS2022 exporter exists ---
if '<VS2017' in txt and '<VS2022' not in txt:
    txt = txt.replace('<VS2017', '<VS2022')
    txt = txt.replace('</VS2017>', '</VS2022>')
    txt = txt.replace('Builds/VisualStudio2017', 'Builds/VisualStudio2022')
    txt = txt.replace('Builds\\VisualStudio2017', 'Builds\\VisualStudio2022')
    txt = re.sub(r'toolset="v14[01]"', 'toolset="v143"', txt)
    print("Retargeted VS2017 exporter -> VS2022")

with open(path, "w", encoding="utf-8") as f:
    f.write(txt)
print(f"Patched {path}: {before} -> {len(txt)} bytes")
